version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongo_db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: ideanest
        networks:
            - nest

    redis:
        image: redis:latest
        restart: always
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - nest
        environment:
            - REDIS_PASSWORD=my-password
            - REDIS_PORT=6379
            - REDIS_DATABASES=16

    server:
        build:
            context: ./server
        container_name: server
        ports:
            - "3000:3000"
        depends_on:
            - mongodb
        environment:
            - DB_URL=mongodb://mongodb:27017/ideanest
            - PORT=3000
            - ACCESS_TOKEN_SECRET=pe3JJMOfV1mZneuLgZnFQnd3dMzHZax3
            - REFRESH_TOKEN_SECRET=dmx06prN1VmAxi0PSSnDXOGOJoRX39qZ
        networks:
            - nest

networks:
    nest:
        driver: bridge
